WebJaguarPortal/ViewModels/CodeViewModel.cs
using WebJaguarPortal.Models;

namespace WebJaguarPortal.ViewModels
{
    public class CodeViewModel
    {
        public string ClassName { get; set; }
        public string FileName { get; set; }
        public string Content { get; set; }
        public string Path { get; internal set; }
        public ICollection<LineAnalysis> Lines { get; set; }
    }
}

WebJaguarPortal/ViewModels/FileManagerItemViewModel.cs
namespace WebJaguarPortal.ViewModels
{
    public class FileManagerItemViewModel
    {
        public bool IsPath { get; set; }
        public bool IsFile { get; set; }
        public string? Name { get; set; }
        public string? Path { get; set; }
        public string? Fullname { get; set; }
        public string? Extension { get; set; }
        public long? IdClass { get; set; }
        public string? Icon
        {
            get
            {
                return Extension switch
                {
                    ".java" => "java",
                    _ => "code",
                };
            }
        }
        public List<FileManagerItemViewModel>? FilesAndPaths { get; set; }
    }
}

WebJaguarPortal/Areas/Api/Controllers/AnalyzesController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Runtime.Intrinsics.Arm;
using WebJaguarPortal.Areas.Api.Models;
using WebJaguarPortal.Infrastructure;
using WebJaguarPortal.Models;
using WebJaguarPortal.Services;

namespace WebJaguarPortal.Areas.Api.Controllers
{
    [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme, Roles = RolesUtil.AnalyzesNew)]
    [Route("api/[controller]")]
    [ApiController]
    public class AnalyzesController : ControllerBase
    {
        private readonly AnalysisService service;
        private readonly IMapper mapper;

        public AnalyzesController(AnalysisService service, IMapper mapper)
        {
            this.service = service;
            this.mapper = mapper;
        }

        [HttpPost]
        [ProducesResponseType(200, Type = typeof(Models.AnalysisControlFlowResponseModel))]
        [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme, Roles = RolesUtil.AnalyzesNew)]
        public IActionResult Initialize(Models.AnalysisControlFlowModel model)
        {
            ControlFlowAnalysis analysis = new ControlFlowAnalysis()
            {
                TestsFail = model.TestsFail,
                TestsPass = model.TestsPass,
                Provider = model.Provider,
                Repository = model.Repository,
                PullRequestBase = model.PullRequestBase ?? string.Empty,
                PullRequestBranch = model.PullRequestBranch ?? string.Empty,
                PullRequestNumber = model.PullRequestNumber ?? string.Empty
            };

            long id = service.New(model.ProjectKey, analysis);
            return Ok(new Models.AnalysisControlFlowResponseModel { Id = id });
        }

        [HttpPost]
        [Route("{id}/Finalize")]
        [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme, Roles = RolesUtil.AnalyzesNew)]
        public IActionResult Finalize([FromRoute] long id, [FromBody] FinalizeAnalysisModel model)
        {
            switch (model.Status)
            {
                case FinalizeAnalysisModel.StatusFinalize.Success:
                    service.FinalizeSuccess(id);
                    break;
                case FinalizeAnalysisModel.StatusFinalize.Error:
                    if (model?.MessageError != null)
                    {
                        service.FinalizeError(id, model.MessageError);
                    }
                    else
                    {
                        ModelState.AddModelError(nameof(model.MessageError), $"{nameof(model.MessageError)} is required to finalize with error.");
                        return BadRequest(ModelState);
                    }
                    break;
            }
            return Ok();
        }

        [HttpPost]
        [Route("{id}/Class")]
        [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme, Roles = RolesUtil.AnalyzesNew)]
        public IActionResult Post([FromRoute] long id, [FromBody] Models.ClassAnalysisModel model)
        {
            ClassAnalysis classAnalysis = new()
            {
                AnalysisId = id,
                FullName = model.FullName,
                Lines = new List<LineAnalysis>()
            };

            if (model.Code != null && model.Code.Length > 0)
            {
                if (service.VerifyExistsFile(model.Code, out long? idFile) && idFile.HasValue)
                {
                    classAnalysis.FileAnalyzeId = idFile.Value;
                }
                else
                {
                    classAnalysis.Code = new FileAnalysis()
                    {
                        Data = model.Code,
                        Hash = Util.GenerateMD5(model.Code)
                    };
                }
            }

            foreach (var item in model.Lines)
            {
                classAnalysis.Lines.Add(new LineAnalysis()
                {
                    Cef = item.Cef,
                    Cep = item.Cep,
                    Cnf = item.Cnf,
                    Cnp = item.Cnp,
                    NumberLine = item.NumberLine,
                    SuspiciousValue = item.SuspiciousValue,
                    Method = item.Method,
                    ClassAnalysisId = id
                });
            }

            service.AddClass(classAnalysis);
            return Ok();
        }
    }
}

WebJaguarPortal/Controllers/AnalyzesController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections;
using System.Text;
using WebJaguarPortal.Infrastructure;
using WebJaguarPortal.Models;
using WebJaguarPortal.Repository.Interfaces;
using WebJaguarPortal.Services;
using WebJaguarPortal.ViewModels;

namespace WebJaguarPortal.Controllers
{
    [ApiExplorerSettings(IgnoreApi = true)]
    [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
    public class AnalyzesController : Controller
    {
        private readonly ILogger<AnalyzesController> _logger;
        private readonly AnalysisService analysisService;
        private readonly IMapper mapper;

        public AnalyzesController(ILogger<AnalyzesController> logger, AnalysisService analysisService, IMapper mapper)
        {
            _logger = logger;
            this.analysisService = analysisService;
            this.mapper = mapper;
        }

        [HttpGet]
        [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme, Roles = RolesUtil.AnalyzesList)]
        public IActionResult Index()
        {
            List<AnalyzeGridItemViewModel> list = new List<AnalyzeGridItemViewModel>();
            foreach (var item in analysisService.GetAll())
            {
                list.Add(new AnalyzeGridItemViewModel()
                {
                    CreatedAt = item.StartAnalysis,
                    Status = item.Status == Models.StatusAnalysis.InProgress ? "In progess" : item.Status == Models.StatusAnalysis.Completed ? "Completed" : "Error",
                    ProjectName = item.Project.Name,
                    Id = item.Id,
                    TestsFail = item.TestsFail,
                    TestsPass = item.TestsPass,
                    PullRequestBase = item.PullRequestBase,
                    PullRequestBranch = item.PullRequestBranch,
                    PullRequestNumber = item.PullRequestNumber,
                    Provider = item.Provider,
                    Repository = item.Repository,
                    UpdatedAt = item.EndAnalysis
                });
            }

            return View("Index", list);
        }

        [HttpGet]
        [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme, Roles = RolesUtil.AnalyzesList)]
        public IActionResult Project(long id)
        {
            List<AnalyzeGridItemViewModel> list = new List<AnalyzeGridItemViewModel>();
            foreach (var item in analysisService.GetAll().Where(x => x.ProjectId == id))
            {
                list.Add(new AnalyzeGridItemViewModel()
                {
                    CreatedAt = item.StartAnalysis,
                    Status = item.Status == Models.StatusAnalysis.InProgress ? "In progess" : item.Status == Models.StatusAnalysis.Completed ? "Completed" : "Error",
                    ProjectName = item.Project.Name,
                    Id = item.Id,
                    TestsFail = item.TestsFail,
                    TestsPass = item.TestsPass,
                    PullRequestBase = item.PullRequestBase,
                    PullRequestBranch = item.PullRequestBranch,
                    PullRequestNumber = item.PullRequestNumber,
                    Provider = item.Provider,
                    Repository = item.Repository,
                    UpdatedAt = item.EndAnalysis,

                });
            }

            return View("Index", list);
        }

        [HttpGet]
        [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme, Roles = RolesUtil.AnalyzesDetail)]
        public IActionResult Detail(long id)
        {
            AnalyzeDetailViewModel detail = new AnalyzeDetailViewModel();

            IEnumerable<ClassAnalysis> classes = analysisService.GetById(id).Classes;

            IEnumerable<string> files = classes.Select(x => x.FullName);
            
            detail.FilesAndPaths = analysisService.Convert(classes, files);

            List<ViewModels.LineAnalysisViewModel> lines = new List<ViewModels.LineAnalysisViewModel>();

            foreach (var item in analysisService.GetById(id).Classes)
            {
                foreach (var lineX in item.Lines)
                {
                    LineAnalysisViewModel line = mapper.Map<ViewModels.LineAnalysisViewModel>(lineX);
                    line.ClassName = item.FullName;
                    lines.Add(line);
                }
            }

            detail.Susp = lines;

            return View(detail);
        }


        [HttpGet]
        [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme, Roles = RolesUtil.AnalyzesDelete)]
        public IActionResult Delete(long id)
        {
            var item = analysisService.GetById(id);
            if (item == null)
            {
                TempData["AlertFade"] = "Analysis not found";
                return RedirectToAction("Index");
            }

            AnalyzeDeleteViewModel obj = new()
            {
                CreatedAt = item.StartAnalysis,
                ProjectName = item.Project.Name,
                Id = item.Id,
                Repository = item.Repository,
            };
            return View("Delete", obj);
        }

        [HttpPost]
        [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme, Roles = RolesUtil.AnalyzesDelete)]
        public IActionResult Delete(AnalyzeDeleteViewModel model)
        {
            if (ModelState.IsValid)
            {
                analysisService.Delete(model.Id);

                TempData["AlertFade"] = "Analysis successfully deleted";
                return RedirectToAction("Index");
            }

            return View("Delete", model);
        }

        [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme, Roles = RolesUtil.AnalyzesDetail)]
        public PartialViewResult Code(long id)
        {
            var @class = analysisService.GetClassById(id);
            var file = @class.Code;

            string path = string.Empty;
            string className = string.Empty;

            int indiceUltimoBarra = @class.FullName.LastIndexOf('/');
            if (indiceUltimoBarra >= 0)
            {
                path = @class.FullName.Substring(0, indiceUltimoBarra + 1);
                className = @class.FullName.Substring(indiceUltimoBarra + 1, @class.FullName.Length - indiceUltimoBarra - 1);
            }

            CodeViewModel code = new CodeViewModel()
            {
                ClassName = className,
                Content = file != null ? Encoding.UTF8.GetString(file.Data) : string.Empty,
                FileName = $"{className}.java",
                Path = path,
                Lines = @class.Lines
            };

            return PartialView("_code", code);
        }
    }
}

WebJaguarPortal/Controllers/ProjectsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebJaguarPortal.Infrastructure;
using WebJaguarPortal.Models;
using WebJaguarPortal.Services;
using WebJaguarPortal.ViewModels;

namespace WebJaguarPortal.Controllers
{
    [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
    public class ProjectsController : Controller
    {
        private readonly ILogger<ProjectsController> _logger;
        private readonly ProjectService projectService;
        private readonly IMapper mapper;

        public ProjectsController(ILogger<ProjectsController> logger, ProjectService projectService, IMapper mapper)
        {
            _logger = logger;
            this.projectService = projectService;
            this.mapper = mapper;
        }

        [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme, Roles = RolesUtil.ProjectsList)]
        public IActionResult Index()
        {
            IEnumerable<ProjectGridViewModel> list = mapper.Map<IEnumerable<ProjectGridViewModel>>(projectService.GetAll());

            return View(list);
        }

        [HttpGet]
        [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme, Roles = RolesUtil.ProjectsNew)]
        public IActionResult Add()
        {
            return View("Add", new ProjectAddViewModel());
        }

        [HttpPost]
        [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme, Roles = RolesUtil.ProjectsNew)]
        public IActionResult Add(ProjectAddViewModel model)
        {
            if (ModelState.IsValid)
            {
                Project proj = mapper.Map<Project>(model);
                projectService.Add(proj);

                TempData["AlertFade"] = "Project successfully added";
                return RedirectToAction("Index");
            }

            return View("Add", model);
        }

        [HttpGet]
        [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme, Roles = RolesUtil.ProjectsDetail)]
        public IActionResult Detail(long id)
        {
            var project = projectService.GetById(id);

            ProjectDetailViewModel proj = mapper.Map<ProjectDetailViewModel>(project);

            return View("Detail", proj);
        }

        [HttpGet]
        [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme, Roles = RolesUtil.ProjectsEdit)]
        public IActionResult Edit(long id)
        {
            var project = projectService.GetById(id);

            ProjectEditViewModel proj = mapper.Map<ProjectEditViewModel>(project);

            return View("Edit", proj);
        }

        [HttpPost]
        [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme, Roles = RolesUtil.ProjectsEdit)]
        public IActionResult Edit(ProjectEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                Project proj = mapper.Map<Project>(model);
                projectService.Update(proj);

                TempData["AlertFade"] = "Project successfully edited";
                return RedirectToAction("Index");
            }

            return View("Add", model);
        }


        [HttpGet]
        [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme, Roles = RolesUtil.ProjectsDelete)]
        public IActionResult Delete(long id)
        {
            var project = projectService.GetById(id);

            ProjectDeleteViewModel proj = mapper.Map<ProjectDeleteViewModel>(project);

            return View("Delete", proj);
        }

        [HttpPost]
        [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme, Roles = RolesUtil.ProjectsDelete)]
        public IActionResult Delete(ProjectDeleteViewModel model)
        {
            if (ModelState.IsValid)
            {
                projectService.Delete(model.Id);

                TempData["AlertFade"] = "Project successfully deleted";
                return RedirectToAction("Index");
            }

            return View("Delete", model);
        }
    }
}

WebJaguarPortal/Views/Analyzes/Delete.cshtml
@model AnalyzeDeleteViewModel
@{
    ViewData["Title"] = "Analysis";
}

<div class="container-fluid uniquePanel">

    <h1>Delete Analysis</h1>
    <h4>Are you sure you want to delete this?</h4>

    <h5></h5>
    <form method="post">
        <div class="row">
            <div class="col-xl-3 col-lg-6">
                <input asp-for="Id" type="hidden" class="form-control">


                <div class="form-group mb-2">
                    <label asp-for="ProjectName"></label>
                    <input asp-for="ProjectName" type="text" class="form-control" readonly>
                </div>
                <div class="form-group mb-2">
                    <label asp-for="Repository"></label>
                    <input asp-for="Repository" type="text" class="form-control" readonly>
                </div>

                <div class="form-group mb-2">
                    <label asp-for="CreatedAt"></label>
                    <input asp-for="CreatedAt" type="text" class="form-control" readonly>
                </div>

                <div class="text-danger">
                    @Html.ValidationSummary()
                </div>

                <div class="float-end">
                    <a href="@Url.Action("Index","Projects")" class="btn btn-outline-danger btn-light">Cancel</a>
                    <button class="btn btn-danger">Delete</button>
                </div>
            </div>
        </div>
    </form>

</div>

WebJaguarPortal/Views/Analyzes/Detail.cshtml
@model AnalyzeDetailViewModel
@{
    ViewData["Title"] = "Analysis";
}

<script>
    var endpointCode = '@Url.Action("Code", "Analyzes")'
</script>


<div class="left-panel">
    <div class="form-group d-none">


        <input class="form-control" id="last_action" type="text" size="15" placeholder="Search" readonly="">

        @*<input type="text" class="form-control" id="search" aria-describedby="search" placeholder="Search">*@

    </div>

    <div class="bar-title">
        <ul class="title">
            <li class="selected">Files</li>
            @*<li>File manager</li>*@
        </ul>
    </div>


    <div class="tree">
        <ul role="tree" aria-labelledby="tree_label">

            @{
                await Html.RenderPartialAsync("_fileManagerItem", @Model.FilesAndPaths);
            }
        </ul>
    </div>
@*
    <div class="tree">
        <ul role="tree" aria-labelledby="tree_label">
            <li role="treeitem" aria-expanded="false" aria-selected="false">
                <span> Projects </span>
                <ul role="group">
                    <li role="treeitem" aria-selected="false" class="doc">project-1.docx</li>
                    <li role="treeitem" aria-selected="false" class="doc">project-2.docx</li>
                    <li role="treeitem" aria-expanded="false" aria-selected="false">
                        <span> Project 3 </span>
                        <ul role="group">
                            <li role="treeitem" aria-selected="false" class="doc">project-3A.docx</li>
                            <li role="treeitem" aria-selected="false" class="doc">project-3B.docx</li>
                            <li role="treeitem" aria-selected="false" class="doc">project-3C.docx</li>
                        </ul>
                    </li>
                    <li role="treeitem" aria-selected="false" class="doc">project-4.docx</li>
                    <li role="treeitem" aria-expanded="false" aria-selected="false">
                        <span> Project 5 </span>
                        <ul role="group">
                            <li role="treeitem" aria-selected="false" class="doc">project-5A.docx</li>
                            <li role="treeitem" aria-selected="false" class="doc">project-5B.docx</li>
                            <li role="treeitem" aria-selected="false" class="doc">project-5C.docx</li>
                            <li role="treeitem" aria-selected="false" class="doc">project-5D.docx</li>
                            <li role="treeitem" aria-selected="false" class="doc">project-5E.docx</li>
                            <li role="treeitem" aria-selected="false" class="doc">project-5F.docx</li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li role="treeitem" aria-expanded="false" aria-selected="false">
                <span> Reports </span>
                <ul role="group">
                    <li role="treeitem" aria-expanded="false" aria-selected="false">
                        <span> report-1 </span>
                        <ul role="group">
                            <li role="treeitem" aria-selected="false" class="doc">report-1A.docx</li>
                            <li role="treeitem" aria-selected="false" class="doc">report-1B.docx</li>
                            <li role="treeitem" aria-selected="false" class="doc">report-1C.docx</li>
                        </ul>
                    </li>
                    <li role="treeitem" aria-expanded="false" aria-selected="false">
                        <span> report-2 </span>
                        <ul role="group">
                            <li role="treeitem" aria-selected="false" class="doc">report-2A.docx</li>
                            <li role="treeitem" aria-selected="false" class="doc">report-2B.docx</li>
                            <li role="treeitem" aria-selected="false" class="doc">report-2C.docx</li>
                            <li role="treeitem" aria-selected="false" class="doc">report-2D.docx</li>
                        </ul>
                    </li>
                    <li role="treeitem" aria-expanded="false" aria-selected="false">
                        <span> report-3 </span>
                        <ul role="group">
                            <li role="treeitem" aria-selected="false" class="doc">report-3A.docx</li>
                            <li role="treeitem" aria-selected="false" class="doc">report-3B.docx</li>
                            <li role="treeitem" aria-selected="false" class="doc">report-3C.docx</li>
                            <li role="treeitem" aria-selected="false" class="doc">report-3D.docx</li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li role="treeitem" aria-expanded="false" aria-selected="false">
                <span> Letters </span>
                <ul role="group">
                    <li role="treeitem" aria-expanded="false" aria-selected="false">
                        <span> letter-1 </span>
                        <ul>
                            <li role="treeitem" aria-selected="false" class="doc">letter-1A.docx</li>
                            <li role="treeitem" aria-selected="false" class="doc">letter-1B.docx</li>
                            <li role="treeitem" aria-selected="false" class="doc">letter-1C.docx</li>
                        </ul>
                    </li>
                    <li role="treeitem" aria-expanded="false" aria-selected="false">
                        <span> letter-2 </span>
                        <ul role="group">
                            <li role="treeitem" aria-selected="false" class="doc">letter-2A.docx</li>
                            <li role="treeitem" aria-selected="false" class="doc">letter-2B.docx</li>
                            <li role="treeitem" aria-selected="false" class="doc">letter-2C.docx</li>
                            <li role="treeitem" aria-selected="false" class="doc">letter-2D.docx</li>
                        </ul>
                    </li>
                    <li role="treeitem" aria-expanded="false" aria-selected="false">
                        <span> letter-3 </span>
                        <ul role="group">
                            <li role="treeitem" aria-selected="false" class="doc">letter-3A.docx</li>
                            <li role="treeitem" aria-selected="false" class="doc">letter-3B.docx</li>
                            <li role="treeitem" aria-selected="false" class="doc">letter-3C.docx</li>
                            <li role="treeitem" aria-selected="false" class="doc">letter-3D.docx</li>
                        </ul>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
*@

</div>

<div class="right-panel">
    <div class="top-panel">
        <div id="principal">
        </div>
    </div>
    <div class="bottom-panel">
        @{
            await Html.RenderPartialAsync("_susp", @Model.Susp);
        }

    </div>
</div>

WebJaguarPortal/Views/Analyzes/Index.cshtml
@model IEnumerable<AnalyzeGridItemViewModel>
@{
    ViewData["Title"] = "Analyzes";
}

<div class="container-fluid uniquePanel">

    <div class="row">
        <div class="col">
            <h1>Analyzes</h1>

            <table class="table table-striped table-hover table-borderless table-dark align-middle">
                <thead>
                    <tr>
                        <td>
                            Project Name
                        </td>
                        <td>
                            Repository
                        </td>
                        <td>
                            Pull Request
                        </td>
                        <td>
                            Status
                        </td>
                        <td>
                            Tests Pass/Total
                        </td>
                        <td>
                            Created at
                        </td>
                        <td>
                            Updated at
                        </td>
                        <td></td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.ProjectName</td>
                            <td>
                                @if (!string.IsNullOrEmpty(item.RepositoryUrl))
                                {
                                    <a target="_blank" href="@item.RepositoryUrl">@item.Repository</a>
                                }
                                else
                                {
                                    @item.Repository
                                }
                            </td>
                            <td>
                                @if (!string.IsNullOrEmpty(item.PullRequestUrl))
                                {
                                    <a target="_blank" href="@item.PullRequestUrl">#@item.PullRequestNumber - @item.PullRequestFromTo</a>
                                }
                            </td>
                            <td>@item.Status</td>
                            <td>@Html.Raw($"{item.TestsPass}/{item.TestsFail + @item.TestsPass}")</td>
                            <td>@item.CreatedAt</td>
                            <td>@item.UpdatedAt</td>
                            <td class="text-end">
                                @if (User.IsInRole(WebJaguarPortal.Infrastructure.RolesUtil.AnalyzesDetail))
                                {
                                    <a class="btn btn-primary" href="@Url.Action("Detail","Analyzes", new {id = item.Id})" title="Detail">
                                        <i class="fa-solid fa-eye fa-lg"></i> DETAIL
                                    </a>
                                }
                                @if (User.IsInRole(WebJaguarPortal.Infrastructure.RolesUtil.AnalyzesDelete))
                                {
                                    <a class="btn btn-primary" href="@Url.Action("Delete","Analyzes", new {id = item.Id})" title="Delete">
                                        <i class="fa-solid fa-trash-can fa-lg"></i> DELETE
                                    </a>
                                }
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

WebJaguarPortal/Views/Analyzes/_code.cshtml
@model CodeViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="bar-title">
    <ul>
        <li class="selected">
            <span data-toggle="tooltip" title="Class @Model.ClassName, in @Model.Path\@Model.FileName">@Model.FileName</span>
        </li>
    </ul>
</div>
<pre class="code">@Model.Content</pre>


<script>
    var objSusp = {
        A1: [],
        A2: [],
        A3: [],
        A4: [],
        A5: []
    }
</script>
@foreach (var item in @Model.Lines)
{
    if (item.SuspiciousValue > 0.8)
    {
        <script>objSusp.A1.push([@item.NumberLine,@item.SuspiciousValue])</script>
    }
    else if (item.SuspiciousValue > 0.6)
    {
        <script>objSusp.A2.push([@item.NumberLine,@item.SuspiciousValue])</script>
    }
    else if (item.SuspiciousValue > 0.4)
    {
        <script>objSusp.A3.push([@item.NumberLine,@item.SuspiciousValue])</script>
    }
    else if (item.SuspiciousValue > 0.2)
    {
        <script>objSusp.A4.push([@item.NumberLine, @item.SuspiciousValue])</script>
    }
    else
    {
        <script>objSusp.A5.push([@item.NumberLine, @item.SuspiciousValue])</script>
    }
}

WebJaguarPortal/Views/Analyzes/_fileManagerItem.cshtml
@model IEnumerable<FileManagerItemViewModel>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@foreach (var item in Model)
{
    if (item.IsPath)
    {
        <li role="treeitem" aria-expanded="false" aria-selected="false">
            <span> @item.Name </span>
            @if (item.FilesAndPaths != null && item.FilesAndPaths.Count() > 0)
            {
                <ul role="group">
                    @{await Html.RenderPartialAsync("_fileManagerItem", item.FilesAndPaths);}
                </ul>
            }
        </li>
    }
    else if (item.IsFile)
    {
        <li role="treeitem" aria-selected="false" data-idcode="@item.IdClass" class="@item.Icon">@item.Name</li>
    }
}